"""Application configuration loaded from environment variables.

All sensitive values MUST be supplied via environment variables. The application
refuses to start when a required production secret is missing, and explicit
"development" defaults are only allowed when running outside of production
(``APP_ENV`` is not set to ``production``).
"""
from __future__ import annotations

import os
import secrets
from functools import lru_cache
from typing import List

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


# Known insecure default that used to be hard-coded into the application.
# Any value equal to this string is treated as "not configured" by the
# validators, so old committed ``.env`` files do not silently weaken prod.
_KNOWN_INSECURE_SECRET_MARKERS = frozenset(
    {
        "dev-only-insecure-secret-do-not-use-in-prod",
        "dev-secret-key-change-this-in-production",
        "dev-secret-key-change-in-production",
        "",
    }
)

_DEV_DATABASE_FALLBACK = (
    "postgresql+asyncpg://santiago:password123@localhost:5432/petroquery_db"
)
_DEV_CORS_FALLBACK = "http://localhost:3000"

# Known dev/localhost DSNs that should never be accepted in production.
_KNOWN_DEV_DATABASE_MARKERS = frozenset(
    {
        _DEV_DATABASE_FALLBACK,
        "postgresql+asyncpg://santiago:password123@localhost:5432/petroquery_db",
        "",
    }
)


def _is_configured(value: str) -> bool:
    """Return True when ``value`` looks like a real configured secret."""
    return value not in _KNOWN_INSECURE_SECRET_MARKERS


def _is_configured_database(value: str) -> bool:
    """Return True when the DSN doesn't look like a hard-coded dev fallback."""
    return value not in _KNOWN_DEV_DATABASE_MARKERS


class Settings(BaseSettings):
    """Strongly-typed application settings.

    Configuration sources (in priority order):
        1. Process environment variables
        2. ``.env`` file in the working directory
        3. Explicit dev-only fallbacks (disabled when ``APP_ENV=production``)
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    app_env: str = Field(
        default="development",
        description="Environment name. Set to 'production' to require explicit secrets.",
    )

    # --- Required production secrets -----------------------------------------
    secret_key: str = Field(
        default="",
        description=(
            "HMAC key used to sign JWT access tokens. Required in production; "
            "an ephemeral key is generated in development to make local runs "
            "explicit about their insecure nature."
        ),
    )

    # --- Optional but recommended values ------------------------------------
    groq_api_key: str = Field(default="")
    database_url: str = Field(default="")
    db_echo: bool = Field(default=False)
    huggingface_token: str = Field(default="")
    opencode_api_key: str = Field(default="")

    # --- CORS configuration --------------------------------------------------
    # Comma-separated list of allowed origins. Use ``*`` only in development
    # and never together with ``allow_credentials=True`` (browser would block
    # credentialed requests with a wildcard anyway).
    cors_allowed_origins: str = Field(
        default=_DEV_CORS_FALLBACK,
        description=(
            "Comma-separated list of origins allowed by CORS. Example: "
            "'https://app.example.com,http://localhost:3000'."
        ),
    )

    # --- Internal controls ---------------------------------------------------
    invite_temp_password_to_log: bool = Field(
        default=False,
        validation_alias="INVITE_LOG_TEMP_PASSWORD",
        description=(
            "When true, the temporary password generated by the admin invite "
            "endpoint is printed to stdout. MUST be false in production. "
            "Intended for local development only."
        ),
    )
    max_upload_size_mb: int = Field(default=25, ge=1, le=250)
    prewarm_model_on_startup: bool = Field(default=False)

    # --- Auth: HttpOnly access-token cookie ---------------------------------
    # When enabled, `/auth/login` also sets an HttpOnly `access_token` cookie
    # so SPAs that support credentials can drop the localStorage approach.
    # The JSON response still carries the token for clients that prefer the
    # Authorization header.
    auth_cookie_enabled: bool = Field(
        default=True,
        description=(
            "When true, /auth/login also sets an HttpOnly access_token cookie. "
            "Set to false to opt out and only return the token in the JSON body."
        ),
    )
    auth_cookie_name: str = Field(
        default="pq_access_token",
        description="Name of the access-token cookie.",
    )
    auth_cookie_secure: bool = Field(
        default=False,
        description=(
            "When true, the access-token cookie is marked Secure. Defaults to "
            "true in production and false in development so the local server "
            "(plain HTTP) keeps working."
        ),
    )
    auth_cookie_samesite: str = Field(
        default="lax",
        description="SameSite policy for the access-token cookie.",
    )

    # --- Rate limiting ------------------------------------------------------
    # The defaults are intentionally process-local (memory://) so a single
    # developer can run the API without standing up Redis. Production
    # deployments should override RATE_LIMIT_STORAGE_URI with a Redis URL
    # so the limit is shared across workers.
    rate_limit_enabled: bool = Field(
        default=True,
        description=(
            "When false, the rate limiter is a no-op. Useful for E2E tests "
            "that need to drive many requests in a row."
        ),
    )
    rate_limit_storage_uri: str = Field(
        default="memory://",
        description=(
            "Storage backend for slowapi/limits. Examples: 'memory://', "
            "'redis://host:6379/0'. Switch to Redis in production."
        ),
    )
    rate_limit_login_per_minute: int = Field(default=10, ge=1, le=1000)
    rate_limit_register_per_minute: int = Field(default=5, ge=1, le=1000)

    # -------------------------------------------------------------------------
    # Validators
    # -------------------------------------------------------------------------
    @field_validator("secret_key")
    @classmethod
    def _validate_secret_key(cls, value: str, info) -> str:
        env = (info.data.get("app_env") or "development").lower()
        if env == "production":
            if value in _KNOWN_INSECURE_SECRET_MARKERS:
                raise ValueError(
                    "SECRET_KEY must be set to a strong random value when "
                    "APP_ENV=production. The default insecure placeholder "
                    "value is rejected."
                )
            if len(value) < 32:
                raise ValueError(
                    "SECRET_KEY must be at least 32 characters long in production."
                )
            return value
        if not _is_configured(value):
            # Development fallback: generate a per-process random key and warn.
            # This prevents the previous "insecure shared default" behaviour
            # while still letting the app start locally without a real secret.
            generated = secrets.token_urlsafe(48)
            print(
                "[WARN] SECRET_KEY not set; generated an ephemeral random key. "
                "Tokens will not survive a restart. Set SECRET_KEY in your .env "
                "to silence this warning."
            )
            return generated
        return value

    @field_validator("database_url")
    @classmethod
    def _validate_database_url(cls, value: str, info) -> str:
        env = (info.data.get("app_env") or "development").lower()
        if env == "production" and not _is_configured_database(value):
            raise ValueError(
                "DATABASE_URL must be set to a real production DSN when "
                "APP_ENV=production. The dev/localhost default is rejected."
            )
        if not _is_configured_database(value):
            return _DEV_DATABASE_FALLBACK
        return value

    @field_validator("cors_allowed_origins")
    @classmethod
    def _validate_cors_origins(cls, value: str, info) -> str:
        env = (info.data.get("app_env") or "development").lower()
        if env == "production":
            origins = [o.strip() for o in value.split(",") if o.strip()]
            if "*" in origins:
                raise ValueError(
                    "Wildcard '*' is not allowed in CORS_ALLOWED_ORIGINS when "
                    "APP_ENV=production."
                )
            if not origins:
                raise ValueError(
                    "CORS_ALLOWED_ORIGINS must list at least one origin in "
                    "production."
                )
        return value

    @field_validator("invite_temp_password_to_log")
    @classmethod
    def _validate_invite_password_logging(cls, value: bool, info) -> bool:
        env = (info.data.get("app_env") or "development").lower()
        if env == "production" and value:
            raise ValueError(
                "INVITE_LOG_TEMP_PASSWORD must be false in production."
            )
        return value

    @field_validator("auth_cookie_secure", mode="before")
    @classmethod
    def _default_cookie_secure(cls, value, info) -> bool:
        """Default the cookie's Secure flag to true in production."""
        if value is None or value == "":
            env = (info.data.get("app_env") or "development").lower()
            return env == "production"
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "yes", "on"}
        return bool(value)

    @field_validator("auth_cookie_samesite")
    @classmethod
    def _validate_cookie_samesite(cls, value: str) -> str:
        normalised = (value or "").strip().lower()
        if normalised not in {"lax", "strict", "none"}:
            raise ValueError(
                "AUTH_COOKIE_SAMESITE must be one of: lax, strict, none."
            )
        return normalised

    # -------------------------------------------------------------------------
    # Derived helpers
    # -------------------------------------------------------------------------
    @property
    def is_production(self) -> bool:
        return (self.app_env or "").lower() == "production"

    @property
    def cors_origins_list(self) -> List[str]:
        """Return CORS origins as a list, trimmed and empty strings removed."""
        if not self.cors_allowed_origins:
            return []
        return [origin.strip() for origin in self.cors_allowed_origins.split(",") if origin.strip()]

    @property
    def cors_allow_all(self) -> bool:
        """True only when explicitly configured to allow any origin.

        In production this is always False (validated above)."""
        return "*" in self.cors_origins_list and not self.is_production


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
